#
#  Author: Hari Sekhon
#  Date: 2021-11-23 11:42:08 +0000 (Tue, 23 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#      A r g o C D   R e p o   S e r v e r   R e s o u r c e s   P a t c h
# ============================================================================ #

# run: kubectl patch deploy argocd-repo-server -n argocd --type json --patch "$(cat resources.argocd-repo-server.jsonpatch.yaml)"

---
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      # Goldilocks / VPA recommended 50m CPU but for larger app consistently hitting this error:
      #
      # ComparisonError: rpc error: code = Unknown desc = Manifest generation error (cached): kustomize build /tmp/git@github.com_<owner>_kubernetes/<path> --enable-helm failed timeout after 1m30s
      #
      # See this ticket for more details:
      #
      #   https://github.com/argoproj/argo-cd/issues/9701
      #
      cpu: '1.5'
      memory: 2.5Gi
    limits:
      cpu: '1.5'
      memory: 2.5Gi
