#
#  Author: Hari Sekhon
#  Date: 2023-05-04 23:49:22 +0100 (Thu, 04 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                ArgoCD Notifications Controller Resources Patch
# ============================================================================ #

# run: kubectl patch deploy argocd-notifications-controller -n argocd --type json --patch "$(cat resources.argocd-notifications-controller.jsonpatch.yaml)"

---
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
