#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2022-08-15 16:01:53 +0100 (Mon, 15 Aug 2022)
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Kustomize Materialize
description: Materializes all *-kustomization.yaml to *.kustomization.yaml.materialized so that scanning tools can find problems in the resulting k8s yaml templates

#inputs:
#  debug:
#    description: Enable Debug Mode
#    type: boolean
#    required: false
#    default: false

runs:
  using: composite
  steps:
    - name: Kustomizations Materialize
      shell: bash
      run: |
        echo "Running Kustomizations Materialize Action"
        set -euxo pipefail

        # ==================
        # None of these work
        #git config credential.helper '!f() { sleep 1; echo "username=${GITHUB_USER}"; echo "password=${GITHUB_TOKEN}"; }; f'

        #cat > git_askpass.sh <<EOF
        ##!/bin/sh
        #echo username="$GITHUB_USER"
        #echo password="$GITHUB_TOKEN"
        #EOF
        #chmod +x git_askpass.sh
        #export GIT_ASKPASS="$PWD/git_askpass.sh"

        # works for 'git fetch' but doesn't work in Kustomize
        #git config url."https://token:$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
        #cat .git/config
        # ==================

        # use this to access private repositories because url .insteadOf above only works in 'git fetch' and not in Kustomize
        # must be done in a loop first because kustomizations that include other kustomizations will fail if they aren't all edited first
        #find . -name 'kustomization.y*ml' |
        #while read -r kustomization; do
        #  sed -i "s|-[[:space:]]*github.com/|- https://$GITHUB_TOKEN@github.com/|" "$kustomization"
        #done

        for kustomization in */*/kustomization.y*ml; do
          # XXX: https://github.com/wiremind/wiremind-helm-charts/issues/259
          # XXX: Rancher chart is old- Error: Error: chart requires kubeVersion: < 1.26.0-0 which is incompatible with Kubernetes v1.28.0
          if [[ "$kustomization" =~ clair/|traefik-hub-agent/|rancher/ ]]; then
            continue
          fi
          echo "$kustomization"
          pushd "$(dirname "$kustomization")" >/dev/null
          kustomize build --enable-helm > "kustomization.yaml.materialized"
          echo "Materialized YAML -> kustomization.yaml.materialized"
          popd
          echo
        done
