#
#  Author: Hari Sekhon
#  Date: 2023-04-13 02:03:57 +0100 (Thu, 13 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                         T r a e f i k   S e r v i c e
# ============================================================================ #

---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: NAME  # XXX: Edit
  namespace: NAMESPACE  # XXX: Edit
spec:
  weighted:
    #sticky:
    #  cookie:
    #    name: level1
    services:
      - name: NAMEv1
        port: 80
        namespace: NAMESPACE  # XXX: Edit
        weight: 5
        #sticky:
        #  cookie:
        #    httpOnly: false
        #    name: level2
        #    secure: true
        #    sameSite: strict
      - name: NAMEv2
        port: 80
        weight: 1
        namespace: NAMESPACE  # XXX: Edit
        #sticky:
        #  cookie:
        #    httpOnly: false
        #    name: level2
        #    secure: true
        #    sameSite: strict
  #mirroring:
  #  name: NAMEv1  # main service
  #  port: 80
  #  namespace: NAMESPACE
  #  mirrors:
  #    - name: NAMEv2  # mirrored service - check logs/metrics of how this app behaves, its responses are not routed back to the client
  #      port: 80
  #      namespace: NAMESPACE
  #      percent: 50
