AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestFunction:
    Properties:
      CodeUri: s3://myBucket/1a23456b78901c234d56e78fa9012bc3
      Environment:
        Variables:
          S3_BUCKET: myBucket
      Handler: index.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
