#
#  Author: Hari Sekhon
#  Date: 2021-12-14 17:34:24 +0000 (Tue, 14 Dec 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                     C i r c l e C I   R u n n e r   H P A
# ============================================================================ #

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: circleci-runner
  namespace: circleci
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: circleci-runner
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
