#
#  Author: Hari Sekhon
#  Date: 2022-08-19 16:08:01 +0100 (Fri, 19 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                  B e a t s   f o r   E C K   o p e r a t o r
# ============================================================================ #

# https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-beat.html

---
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: mycluster  # XXX: Edit
spec:
  type: filebeat
  version: 8.3.3
  elasticsearchRef:
    name: mycluster  # XXX: Edit to match elasticsearch-cluster.yaml
  config:
    filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
  daemonSet:
    podTemplate:
      spec:
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true
        securityContext:
          runAsUser: 0
        containers:
          - name: filebeat
            volumeMounts:
              - name: varlogcontainers
                mountPath: /var/log/containers
              - name: varlogpods
                mountPath: /var/log/pods
              - name: varlibdockercontainers
                mountPath: /var/lib/docker/containers
        volumes:
          - name: varlogcontainers
            hostPath:
              path: /var/log/containers
          - name: varlogpods
            hostPath:
              path: /var/log/pods
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
