#
#  Author: Hari Sekhon
#  Date: 2021-06-01 16:37:54 +0100 (Tue, 01 Jun 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                F l u x C D   v 2   S l a c k   P r o v i d e r
# ============================================================================ #

# https://fluxcd.io/docs/guides/notifications/

# 1. First create a Slack webhook as follows:
#
#       https://api.slack.com/messaging/webhooks
#
# 2. Create the Kubernetes secret containing the secret webhook url
#                                                                                         XXX: Edit - replace this URL
#       kubectl -n flux-system create secret generic slack-webhook --from-literal=address=https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
#
# 3. Apply this manifest to create the alert provider:
#
#       kubectl apply -f fluxcd-slack-provider.yaml
#
# 4. Verify:
#
#       flux get alert-providers

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: fluxcd
  secretRef:
    name: slack-webhook
