#
#  Author: Hari Sekhon
#  Date: 2023-04-30 20:11:36 +0100 (Sun, 30 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                      H e l m   C h a r t   f o r   K 3 s
# ============================================================================ #

# Deploys Helm charts using the K3s Helm Controller:
#
#   https://docs.k3s.io/helm
#
#   https://github.com/k3s-io/helm-controller/

# cp to /var/lib/rancher/k3s/server/manifests/some-helm.yaml

# https://docs.k3s.io/helm#helmchart-field-definitions
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: NAME  # XXX: Edit
  namespace: helm-charts  # deploy to a different namespace than the app for separation
spec:
  repo: REPO  # XXX: Edit
  chart: CHART_NAME  # XXX: Edit
  version: VERSION  # XXX: Edit
  targetNamespace: NAMESPACE  # XXX: Edit
  # set takes precedence over valuesContent and HelmChartConfig
  set:
    global.systemDefaultRegistry: ""
  # XXX: Edit
  # or cp helm-chart-config.yaml /var/lib/rancher/k3s/server/manifests/
  valuesContent: |-
    key: value # ... yaml away ...
