#
#  Author: Hari Sekhon
#  Date: 2021-02-23 12:53:33 +0000 (Tue, 23 Feb 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                          J e n k i n s   C I   P o d
# ============================================================================ #

# see Jenkinsfile template referencing this pod template:
#
#   https://github.com/HariSekhon/Templates/blob/master/Jenkinsfile

---
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
  labels:
  app: jenkins-agent
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
spec:
  priorityClassName: high-priority  # requires priorityclass.yaml
  affinity:
    # avoid preemption which can cause build failures
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-preemptible
            operator: DoesNotExist
          - key: eks.amazonaws.com/capacityType
            operator: NotIn
            values:
            - SPOT
          - key: kubernetes.azure.com/scalesetpriority
            operator: NotIn
            values:
            - spot
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          topologyKey: topology.kubernetes.io/zone
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - jenkins-agent
      - weight: 100
        podAffinityTerm:
          topologyKey: kubernetes.io/hostname
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - jenkins-agent
  # needed for argocd container to /home/jenkins/agent/workspace/<pipeline>@tmp/durable-888973f9/jenkins-log.txt, otherwise Permission Denied
  securityContext:
    runAsUser: 0
  containers:
  - name: gcloud-sdk  # do not name this 'jnlp', without that container this'll never come up properly to execute the build
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    imagePullPolicy: Always
    # works without this
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 300m  # actually takes 800m but overcontend rather than spawning too many nodes for bursty workload
        memory: 300Mi # uses around 250Mi
      limits:
        cpu: "1"
        memory: 1Gi
  - name: aws-cli
    image: amazon/aws-cli:2.4.7
    #imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 300m
        memory: 300Mi
      limits:
        cpu: "1"
        memory: 1Gi
  # more containers if you want to run different stages in different containers eg. to 'wget -O- | jq ...'
  - name: jq
    image: stedolan/jq
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  # Skaffold - CI/CD CLI automation tool - also contains jq
  #
  # can find available versions using tool in DevOps Python tools repo (https://github.com/HariSekhon/DevOps-Python-tools):
  #
  #   docker_registry_show_tags.py -H gcr.io -P 443 -S k8s-skaffold/skaffold
  #
  # but latest v1.41.0 seems ahead of publicised release v1.27.0, which is probably more stable:
  #
  #   https://github.com/GoogleContainerTools/skaffold/releases
  #
  - name: skaffold
    image: gcr.io/k8s-skaffold/skaffold:v1.27.0
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  # ArgoCD - to integrate Jenkins CI -> ArgoCD via sync deployment call - https://argoproj.github.io/argo-cd/user-guide/ci_automation/#synchronize-the-app-optional
  - name: argocd
    image: argoproj/argocd:v2.0.3
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  # for gitOpsK8sUpdate Jenkins shared library at https://github.com/HariSekhon/Templates/blob/master/vars/gitOpsK8sUpdate.groovy
  - name: git-kustomize
    image: harisekhon/git-kustomize:latest
    imagePullPolicy: Always
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  - name: terraform
    image: hashicorp/terraform:1.1.2  # XXX: set this to match the Terraform version you need
    #imagePullPolicy: Always
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  - name: terragrunt
    image: alpine/terragrunt:1.1.2  # XXX: set this to match the Terraform version you need
    #imagePullPolicy: Always
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 500Mi
  # generic CLI container
  - name: busybox
    image: busybox
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 200Mi
  #- name: golang
  #  image: golang:1.10
  #  command:
  #    - cat
  #  tty: true
