#
#  Author: Hari Sekhon
#  Date: [% DATE  # 2020-08-19 14:14:11 +0100 (Wed, 19 Aug 2020) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#  run: kubectl --namespace test create -f namespace_limits.yaml
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                    N a m e s p a c e   L i m i t R a n g e
# ============================================================================ #

# https://kubernetes.io/docs/concepts/policy/limit-range/

# https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/limit-range-v1/

---
apiVersion: v1
kind: LimitRange
metadata:
  name: NAME  # XXX: Edit
  namespace: NAMESPACE  # XXX: Edit
spec:
  limits:
      # Default resource requests + limits to assign to a container if unset by the app yaml - make this frugle and force people to right-size their apps in 2 iterations at time of deployment - see Goldilocks to make this easier (yamls to deploy Goldilocks are in this repo)
    - default:
        cpu: 100m
        memory: 100Mi
      defaultRequest:
        cpu: 100m
        memory: 100Mi
      type: Container
    # Limit how large any single object can be created in this namespace
    - max:
        cpu: "4"
        memory: 8Gi
      defaultRequest:
        cpu: "4"
        memory: 8Gi
      type: Container
