#
#  Author: Hari Sekhon
#  Date: 2020-02-16 18:40:53 +0000 (Sun, 16 Feb 2020)
#
#  vim:ts=4:sts=4:sw=4:et
#
#  https://github.com/harisekhon/tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

apiVersion: v1
kind: Namespace
metadata:
  name: production
