#
#  Author: Hari Sekhon
#  Date: 2022-08-05 01:16:06 +0100 (Fri, 05 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                         Octopus Deploy AKS Single PVC
# ============================================================================ #

# https://octopus.com/docs/installation/octopus-server-linux-container/octopus-in-kubernetes

# Use a single volume instead of 3 separate volumes, this means less buckets and potentially less costs (should be trivial)

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: octopus-storage-claim
  namespace: octopus-deploy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 4Gi
