#
#  Author: Hari Sekhon
#  Date: [% DATE  # 2019-11-27 12:19:45 +0000 (Wed, 27 Nov 2019) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 P e r s i s t e n t   V o l u m e   C l a i m
# ============================================================================ #

# https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolumeclaim

# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/

# GKE will automatically create the underlying disk for us using default storage provider's dynamic provisioner

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: APP-dynamic-pvc
  namespace: NAMESPACE
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
