#
#  Author: Hari Sekhon
#  Date: 2020-08-22 17:10:22 +0100 (Sat, 22 Aug 2020)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 P e r s i s t e n t   V o l u m e   -   N F S
# ============================================================================ #

# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: APP-pv-nfs
  namespace: NAMESPACE
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs-exported
    server: SERVER   # XXX: Edit
    readOnly: false
