#
#  Author: Hari Sekhon
#  Date: 2023-05-01 04:28:41 +0100 (Mon, 01 May 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#  kics-scan ignore
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                    P u s h   E x t e r n a l   S e c r e t
# ============================================================================ #

# https://external-secrets.io/v0.8.1/api/pushsecret/

---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: NAME  # XXX: Edit
  namespace: NAMESPACE # XXX: Edit - same of the SecretStores
spec:
  refreshInterval: 5m
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: aws-secrets-manager
      kind: SecretStore
    #- name: gcp-secret-manager
    #  kind: SecretStore
  selector:
    secret:
      name: some-k8s-secret # XXX: Edit source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: some-key-within-secret # XXX: Edit source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: cloud-secret-name # XXX: Edit - remote reference (where the secret is going to be pushed)
