#
#  Author: Hari Sekhon
#  Date: [% DATE  # 2020-08-22 17:17:00 +0100 (Sat, 22 Aug 2020) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                           R e s o u r c e Q u o t a
# ============================================================================ #

# https://kubernetes.io/docs/concepts/policy/resource-quotas/

# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace/

# https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace/

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: NAME  # XXX: Edit - name it after which settings you enable in the spec, or just name it after the namespace if you're doing all in one quota
  namespace: NAMESPACE  # XXX: Edit
spec:
  hard:
    # XXX: Edit - these are mere arbitrary starting defaults - tune to your expectations
    pods: "50"
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "10"
    limits.memory: 20Gi
    persistentvolumeclaims: "10"
    requests.storage: 50Gi
