#
#  Author: Hari Sekhon
#  Date: [% DATE  # 2021-01-13 15:42:59 +0000 (Wed, 13 Jan 2021) %]
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                          S e r v i c e A c c o u n t
# ============================================================================ #

# https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/service-account-v1/

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: NAME  # XXX: Edit
  namespace: NAME  # XXX: Edit

  annotations:
    # XXX: pick one of the below

    # ============================================================================ #
    #                                     A W S
    # ============================================================================ #

    # AWS IRSA

    # XXX: Edit AW Account ID number 123456789012 + Role name MYAPP
    eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/EKSIrsaMYAPP"

    # ============================================================================ #
    #                                     G K E
    # ============================================================================ #

    # GKE Workload Identity integration

    # - map your k8s serviceaccount to a GCP serviceaccount with permissions to access GCP resources
    # - you'll also need to grant GCP IAM permissions for the k8s SA to use the GCP SA:
    #
    # XXX: Edit or Set env vars:  $CLOUDSDK_CORE_PROJECT, $K8_NAMESPACE, $K8_SA, $GSA
    #
    #   gcloud iam service-accounts add-iam-policy-binding --role roles/iam.workloadIdentityUser --member "serviceAccount:$CLOUDSDK_CORE_PROJECT.svc.id.goog[$K8_NAMESPACE/$K8_SA]" "$GSA@$CLOUDSDK_CORE_PROJECT.iam.gserviceaccount.com"

    # XXX: Edit SERVICEACCOUNT + PROJECT_ID
    iam.gke.io/gcp-service-account: SERVICEACCOUNT@PROJECT_ID.iam.gserviceaccount.com

    # ============================================================================ #
    #                                     A K S
    # ============================================================================ #

    # Azure Workload Identity

    # XXX: Edit client + tenant id
    azure.workload.identity/client-id: 1a2bcd34-xxxx-xxxx-xxxx-567e890f123a
    azure.workload.identity/tenant-id: 1a23b45c-xxxx-xxxx-xxxx-6de7f890a1b2
#
# XXX: you may want this set to true for app to access it inside the container at /var/run/secrets/kubernetes.io/serviceaccount/token
automountServiceAccountToken: false
#
# from secret.yaml type 'kubernetes.io/basic-auth'
#secrets:
#  - name: basic-user-pass
