#
#  Author: Hari Sekhon
#  Date: 2019-11-27 12:19:45 +0000 (Wed, 27 Nov 2019)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                  S t o r a g e C l a s s   -   G C P   S S D
# ============================================================================ #

# Storage Class for GCP SSD instead of GCP standard disk

# https://kubernetes.io/docs/concepts/storage/storage-classes/

# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/storage-class-v1/

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # generic name so on another cloud vendor you just replace the storageclass but the deployment / statefulset manifests don't need modifying
  name: ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd  # default: none
volumeBindingMode: WaitForFirstConsumer  # recommended with regional-pd
reclaimPolicy: Retain # for safety, else default: Delete
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.gke.io/zone
        values:
          - europe-west2-a
          - europe-west2-b
          - europe-west2-c
