#
#  Author: Hari Sekhon
#  Date: 2023-07-22 03:37:16 +0100 (Sat, 22 Jul 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                               N a m e s p a c e
# ============================================================================ #

---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus
  labels:
    goldilocks.fairwinds.com/enabled: "true"
