#
#  Author: Hari Sekhon
#  Date: 2022-12-09 22:18:51 +0000 (Fri, 09 Dec 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#     E x t e r n a l   S e c r e t s   -   A W S   S e c r e t   S t o r e
# ============================================================================ #

# https://external-secrets.io/v0.8.1/provider/aws-secrets-manager/

# https://external-secrets.io/v0.8.1/api/secretstore/

# https://external-secrets.io/v0.8.1/api/clustersecretstore/

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  namespace: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2  # XXX: Edit
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets  # XXX: namespace is needed for ClusterSecretStore
