#
#  Author: Hari Sekhon
#  Date: 2023-04-13 12:40:36 +0100 (Thu, 13 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 N g i n x   I n g r e s s   C o n f i g M a p
# ============================================================================ #

# For global settings to apply to all ingresses using this ingress controller

# Superceded by config key in values.yaml

# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/

# https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/docs/examples/customization/custom-configuration/configmap.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  #labels:
  #  app.kubernetes.io/name: ingress-nginx
  #  app.kubernetes.io/part-of: ingress-nginx
data:
  ssl-redirect: "true"
  force-ssl-redirect: "true"

  whitelist-source-range: |
    10.0.0.0/8,
    172.16.0.0/16,
    192.168.0.0/16
  #denylist-source-range: |

  enable-modsecurity: "true"
  enable-owasp-modsecurity-crs: "true"

  #block-user-agents:  # csv separated strings or regex - https://nginx.org/en/docs/http/ngx_http_map_module.html#map
  #block-referers:

  #enable-syslog: true
  #syslog-host: x.x.x.x
  #syslog-port: 514

  #zipkin-collector-host: zipkin-collector.zipkin.svc.cluster.local
  #zipkin-collector-port: 9411
  #zipkin-service-name: nginx
  #zipkin-sample-rate: 1.0

  #jaeger-collector-host: jaeger-agent.jaeger.svc.cluster.local
  #jaeger-collector-port: 6831
  ##jaeger-endpoint:  # takes priority over jaeger-collector-host/port
  #jaeger-service-name: nginx

  #datadog-collector-host: datadog-agent.datadog.svc.cluster.local
  #datadog-collector-port: 8126
  #datadog-service-name: nginx
  #datadog-environmen: prod

  #enable-opentelemetry: true
  #otlp-collector-host: otlp-collector.opentelemetry.svc.cluster.local
  #otlp-collector-port: 4317
  #otel-service-name: nginx

  #main-snippet:     # add to nginx main{} section
  #http-snippet:     # add to nginx http{} section
  #server-snippet:   # add to nginx servers
  #stream-snippet:
  #location-snippet:

  # AWS EKS
  #
  #   https://aws.amazon.com/premiumsupport/knowledge-center/eks-configure-nginx-ingress-controller/
  #
  # more settings needed in the ingress - see ingress.yaml
  #
  #proxy-body-size: 8m
  #proxy-read-timeout: "120"  # default: "60"
  #proxy-send-timeout: "120"  # default: "60"
