#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2022-08-15 15:47:45 +0100 (Mon, 15 Aug 2022)
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Install Kustomize
description: Installs the latest or given version of Kustomize

#inputs:
#  #version:
#  #  description: Kustomize version to install
#  #  type: string
#  #  required: false
#  debug:
#    description: Enable Debug Mode
#    type: boolean
#    required: false
#    default: false

runs:
  using: composite
  steps:
    - name: Install Kustomize
      shell: bash
      run: |
        echo "Running Install Kustomize Action"
        set -euxo pipefail
        owner_repo="kubernetes-sigs/kustomize"
        version="$(
          curl -sSL --fail "https://api.github.com/repos/$owner_repo/releases" |
          jq -r "limit(1; .[] | select(.tag_name | test(\"kustomize\")) | .tag_name)"
        )"
        version="${version##*/}"
        wget -O /tmp/kustomize.tgz "https://github.com/$owner_repo/releases/download/kustomize%2F$version/kustomize_${version}_linux_amd64.tar.gz"
        tar zxvf /tmp/kustomize.tgz -C /usr/local/bin/

    - name: Kustomize Version
      run: kustomize version
      shell: bash
