#
#  Author: Hari Sekhon
#  Date: 2022-07-15 23:08:21 +0100 (Fri, 15 Jul 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                         T e k t o n   P i p e l i n e
# ============================================================================ #

---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy
  namespace: tekton-pipelines
spec:
  #resources:
  #  - name: repo
  #    type: git
  tasks:
    - name: build
      taskRef:
        name: build
      #resources:
      #  inputs:
      #    - name: repo      # the task input name
      #      resource: repo  # this pipeline's resource name
    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build
      #resources:
      #  inputs:
      #    - name: repo      # the task input name
      #      resource: repo  # this pipeline's resource name
