#
#  Author: Hari Sekhon
#  Date: 2022-07-15 21:22:21 +0100 (Fri, 15 Jul 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                          T e k t o n   T a s k R u n
# ============================================================================ #

# CLI equivalent:
#
#   tkn task start mybuild --inputresource repo=myrepo --serviceaccount my-k8s-sa --showlog

---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-build
spec:
  #serviceAccountName: my-k8s-sa  # containing secret ref, see serviceaccount.yaml
  taskRef:
    name: build
  #resources:
  #  inputs:
  #    - name: repo
  #      resourceRef:
  #        name: myrepo
