#
#  Author: Hari Sekhon
#  Date: 2021-05-13 13:06:05 +0100 (Thu, 13 May 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                       S e l e n i u m   G r i d   H u b
# ============================================================================ #

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
  #annotations:
  #  datree.skip/DEPLOYMENT_INCORRECT_REPLICAS_VALUE: replicas not relevant for this deployment
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      priorityClassName: high-priority
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  # gke-preemptible not valid on GKE AutoPilot clusters - remove in that case and leave only gke-spot
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
                  - key: cloud.google.com/gke-spot
                    operator: DoesNotExist
                  - key: eks.amazonaws.com/capacityType
                    operator: NotIn
                    values:
                      - SPOT
                  - key: kubernetes.azure.com/scalesetpriority
                    operator: NotIn
                    values:
                      - spot
      securityContext:
        runAsNonRoot: true
      containers:
        - name: selenium-hub
          #image: selenium/hub:3.141.59
          image: selenium/hub:4.1.2
          ports:
            - containerPort: 4444  # UI
            - containerPort: 5555  # needed for status in webdriver protocol
          env:
            - name: JAVA_OPTS
              value: "-Xms1G -Xmx1G"
            - name: SE_NODE_SESSION_TIMEOUT
              value: "300"  # default
            # these settings are needed to get Grid 3.x hub to register nodes properly
            - name: POOL_MAX
              value: "500"
            - name: GRID_NEW_SESSION_WAIT_TIMEOUT
              value: "-1"
            - name: GRID_JETTY_MAX_THREADS
              value: "-1"
            - name: GRID_NODE_POLLING
              value: "5000"
            - name: GRID_CLEAN_UP_CYCLE
              value: "5000"
            - name: GRID_TIMEOUT
              value: "600"
            - name: GRID_BROWSER_TIMEOUT
              value: "600"
            - name: GRID_MAX_SESSION
              value: "12"
            - name: GRID_UNREGISTER_IF_STILL_DOWN_AFTER
              value: "30000"
          # can take it down under high load as it becomes less responsive
          #readinessProbe:
          #  httpGet:
          #    # don't use /wd/hub/ - it returns HTTP/2 500 if no nodes are attached
          #    #path: /wd/hub/
          #    path: /status
          #    #path: /wd/hub/status
          #    #path: /  # works too
          #    port: 4444
          #  initialDelaySeconds: 10
          #livenessProbe:
          #  httpGet:
          #    path: /status
          #    #path: /wd/hub/status
          #    port: 4444
          #  initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: 4444
            initialDelaySeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4444
            initialDelaySeconds: 30
          resources:
            requests:
              cpu: 500m
              memory: 1.2Gi
            limits:
              cpu: "4"
              memory: 4Gi
