#
#  Author: Hari Sekhon
#  Date: 2023-04-27 15:51:16 +0100 (Thu, 27 Apr 2023)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#              E x t e r n a l   D N S   K u s t o m i z a t i o n
# ============================================================================ #

# https://github.com/kubernetes-sigs/external-dns

# https://artifacthub.io/packages/helm/bitnami/external-dns

# Troubleshooting:
#
#   kubectl logs -f -n external-dns deploy/external-dns
#
#   check --domain-filter setting in values.yaml and deployment.jsonpatch.yaml matches your.domain.com
#
#   check ingresses have their address fields populated by the ingress controller (Nginx, Traefik and Kong in this repo are all tested to do this)

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: external-dns
    repo: https://charts.bitnami.com/bitnami
    version: 6.32.0
    releaseName: external-dns
    namespace: external-dns
    includeCRDs: true
    valuesFile: values.yaml
