#
#  Author: Hari Sekhon
#  Date: 2021-12-14 00:07:08 +0000 (Tue, 14 Dec 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#          C i r c l e C I   R u n n e r   S e r v i c e A c c o u n t
# ============================================================================ #

---
apiVersion: v1
kind: ServiceAccount
metadata:
  #annotations:
  #  iam.gke.io/gcp-service-account: GSA@PROJECT_ID.iam.gserviceaccount.com  # see serviceaccount.yaml for more details
  name: circleci-runner
  namespace: circleci
automountServiceAccountToken: false
