#
#  Author: Hari Sekhon
#  Date: 2024-02-19 20:09:17 +0000 (Mon, 19 Feb 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                   J C a s C   C o n f i g M a p   P a t c h
# ============================================================================ #

# Wholesale JCasC replacement to be able to override it per environment
# eg. to override jenkins agent NFS mounts per environment overlay ie. dev, staging, prod
# pointing to different GCP Filestores in different GCP projects

# be sure to set agent enabled to false and comment the section in ../base/values.yaml to avoid confusion

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jenkins-jcasc-config
  namespace: jenkins
data:
  # unmunge the jcasc-default-config.yaml string with embedded newlines using this command:
  #
  #     kubectl get cm jenkins-jenkins-jcasc-config -o yaml | yq '.data["jcasc-default-config.yaml"]'
  #
  jcasc-default-config.yaml: |-
    jenkins:
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      # XXX: delete this whole securityRealm section if enabling Google auth plugin so that it doesn't revert Jenkins to local admin local
      securityRealm:
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "${chart-admin-username}"
            name: "Jenkins Admin"
            password: "${chart-admin-password}"
      disableRememberMe: false
      mode: NORMAL
      numExecutors: 0
      labelString: ""
      projectNamingStrategy: "standard"
      markupFormatter:
        plainText
      globalNodeProperties:
      - envVars:
          env:
          - key: "MY_ENV_VAR"  # XXX: Edit: whatever system-wide environment variables you need
            value: "my_value"
      clouds:
      - kubernetes:
          containerCapStr: "30"
          defaultsProviderTemplate: ""
          connectTimeout: "5"
          readTimeout: "15"
          jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
          jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
          maxRequestsPerHostStr: "32"
          retentionTimeout: "5"
          waitForPodSec: "600"
          name: "kubernetes"
          namespace: "jenkins"
          serverUrl: "https://kubernetes.default"
          credentialsId: ""
          podLabels:
          - key: "jenkins/jenkins-jenkins-agent"
            value: "true"
          templates:
            - name: "jenkins-agent"
              namespace: "jenkins"
              containers:
              - name: "jnlp"
                alwaysPullImage: true
                args: "^${computer.jnlpmac} ^${computer.name}"
                command:
                envVars:
                  - envVar:
                      key: "JENKINS_URL"
                      value: "http://jenkins.jenkins.svc.cluster.local:8080/"
                image: "jenkins/inbound-agent:3192.v713e3b_039fb_e-5"
                privileged: "false"
                resourceLimitCpu: 512m
                resourceLimitMemory: 512Mi
                resourceRequestCpu: 512m
                resourceRequestMemory: 512Mi
                runAsUser:
                runAsGroup:
                ttyEnabled: false
                workingDir: /home/jenkins/agent
              volumes:
                # XXX: this is the bit that has to vary per environment
                - nfsVolume:
                    mountPath: "/sharedfiles"
                    readOnly: false
                    # quickly compare to your GCP Filestore NFS IP:
                    #
                    #   gcloud filestore instances list --filter="name ~ /${FILESTORE_NAME}$" --format='value(networks[0].ipAddresses[0])'
                    #
                    serverAddress: "x.x.x.x"  # XXX: Edit per environment
                    serverPath: "/server-shared"  # XXX: Edit to path on the NFS server
              idleMinutes: 0
              instanceCap: 2147483647
              label: "jenkins-jenkins-agent "
              nodeUsageMode: "NORMAL"
              podRetention: Never
              showRawYaml: true
              serviceAccount: "jenkins-agent"  # XXX: change if you need to use a specific service account generated for you with GKE Workload Identity integration
              slaveConnectTimeoutStr: "100"
              yaml: |-
                apiVersion: v1
                kind: Pod
                metadata:
                  annotations:
                    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
              yamlMergeStrategy: merge
      crumbIssuer:
        standard:
          excludeClientIPFromCrumb: true
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    unclassified:
      location:
        adminAddress: "devops@domain.com"  # XXX: Edit
        url: "https://jenkins.domain.com"  # XXX: Edit
