#
#  Author: Hari Sekhon
#  Date: 2022-08-18 18:02:00 +0100 (Thu, 18 Aug 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#  lint: k8s
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                 E l a s t i c   C l o u d   N a m e s p a c e
# ============================================================================ #

---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
  labels:
    goldilocks.fairwinds.com/enabled: "true"
